configdirectory: /var/lib/imap
partition-default: /var/spool/imap

servername: mail.example.test
defaultdomain: mail.example.test
virtdomains: userid
admins: admin@example.test

allowplaintext: yes
sasl_pwcheck_method: auxprop
sasl_auxprop_plugin: sasldb
sasl_mech_list: PLAIN LOGIN

autocreate_quota: 0
autocreate_users: anyone
unixhierarchysep: yes

conversations: yes
conversations_db: twoskip
httpmodules: jmap
httpallowcompress: no
jmap_emailsearch_db_path: /var/lib/imap/jmap-email-query-cache.db

search_engine: xapian
search_index_headers: no

smtp_backend: host
smtp_host: 127.0.0.1:1025

master_bind_errors_fatal: yes
